version: '3'
services:
  api_db:
    container_name: api_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trainly
    ports:
      - "5432:5432"
    volumes:
      - ./.db-data:/var/lib/postgresql/data
