# fly.toml app configuration file generated for trainly-api on 2023-11-06T21:45:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trainly-api"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
