name: deploy

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
